

services:
  selenium-hub:
    image: selenium/hub:4.34.0
    container_name: selenium-hub
    platform: linux/amd64
    ports:
    - "4442:4442"
    - "4443:4443"
    - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10
      - GRID_BROWSER_TIMEOUT=60
      - GRID_TIMEOUT=60
  chrome:
    image: selenium/node-chrome:4.34.0
    platform: linux/amd64
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./downloads:/home/seluser/Downloads
    deploy:
      replicas: 1

  firefox:
    image: selenium/node-firefox:4.34.0
    platform: linux/amd64
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./downloads:/home/seluser/Downloads
    deploy:
      replicas: 1

  edge:
    image: selenium/node-edge:4.34.0
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./downloads:/home/seluser/Downloads
    deploy:
      replicas: 1
